### ISSUE TITLE
disable the settings automatic to default after restart and shutdown

### ISSUE THREAD

**Issue by ahmedmaherdev** [nbebaw/boostchanger#4]
it work good but when i shutdown and restart the laptop the settings i made is gone and i must make the settings after the laptop begin running manually

**Comment by nbebaw** [comment]
> it work good but when i shutdown and restart the laptop the settings i made is gone and i must make the settings after the laptop begin running manually

Thank you for opening this Issue. For your security the settings you made will not be saved to the kernel forever. Unfortunately I can do nothing to this because the kernel do it automatically.
